/*
 * Copyright (c) 2019, Arm Limited. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */
#include "region_defs.h"
#include "mcuboot_config/mcuboot_config.h"

#define _HEX(n) 0x##n
#define HEX(n)  _HEX(n)

/* Enumeration that is used by the assemble.py and imgtool\main.py scripts
 * for correct binary generation when nested macros are used
 */

enum image_attributes
{
  RE_FLASH_AREA_SCRATCH_SIZE = FLASH_AREA_SCRATCH_SIZE,
/* area for preparing images */
  RE_IMAGE_FLASH_SECURE_IMAGE_SIZE = (SECURE_IMAGE_MAX_SIZE),
#if MCUBOOT_APP_IMAGE_NUMBER == 2
  RE_IMAGE_FLASH_NON_SECURE_IMAGE_SIZE = (NON_SECURE_IMAGE_MAX_SIZE),
#else
  RE_IMAGE_FLASH_NON_SECURE_IMAGE_SIZE = (NON_SECURE_IMAGE_MAX_SIZE+SECURE_IMAGE_MAX_SIZE),
#endif
/* area for flashing images */
  RE_IMAGE_FLASH_ADDRESS_SECURE = (FLASH_BASE_ADDRESS+FLASH_AREA_0_OFFSET),
  RE_APP_IMAGE_NUMBER = (HEX(MCUBOOT_APP_IMAGE_NUMBER)),
  RE_EXTERNAL_FLASH_ENABLE = (0x0),
#if (MCUBOOT_APP_IMAGE_NUMBER == 2)
  RE_CODE_START_NON_SECURE = (0x0),
  RE_IMAGE_FLASH_ADDRESS_NON_SECURE = (FLASH_BASE_ADDRESS+FLASH_AREA_1_OFFSET),	
  /* area for updates slot address */
#if !defined(MCUBOOT_PRIMARY_ONLY)
  RE_IMAGE_FLASH_SECURE_UPDATE = (FLASH_BASE_ADDRESS+FLASH_AREA_2_OFFSET),
  RE_IMAGE_FLASH_NON_SECURE_UPDATE = (FLASH_BASE_ADDRESS+FLASH_AREA_3_OFFSET),
  RE_PRIMARY_ONLY = (0x0),
#else
  RE_IMAGE_FLASH_SECURE_UPDATE = (FLASH_BASE_ADDRESS+FLASH_AREA_0_OFFSET),
  RE_IMAGE_FLASH_NON_SECURE_UPDATE = (FLASH_BASE_ADDRESS+FLASH_AREA_1_OFFSET),
  RE_PRIMARY_ONLY = (0x1),
#endif /* MCUBOOT_PRIMARY_ONLY */
#else /*(MCUBOOT_APP_IMAGE_NUMBER == 1) */
  RE_CODE_START_NON_SECURE = (0x0),
  RE_IMAGE_FLASH_ADDRESS_NON_SECURE = (0x0),
#if !defined(MCUBOOT_PRIMARY_ONLY)
  RE_IMAGE_FLASH_SECURE_UPDATE = (FLASH_BASE_ADDRESS+FLASH_AREA_2_OFFSET),
  RE_IMAGE_FLASH_NON_SECURE_UPDATE = (0x0),
  RE_PRIMARY_ONLY = (0x0),
#else
  RE_IMAGE_FLASH_SECURE_UPDATE = (FLASH_BASE_ADDRESS+FLASH_AREA_0_OFFSET),
  RE_IMAGE_FLASH_NON_SECURE_UPDATE = (0x0),
  RE_PRIMARY_ONLY = (0x1),
#endif /* MCUBOOT_PRIMARY_ONLY */
#endif /* (MCUBOOT_APP_IMAGE_NUMBER == 2) */
  RE_S_DATA_IMAGE_NUMBER = (HEX(MCUBOOT_S_DATA_IMAGE_NUMBER)),
#if (MCUBOOT_S_DATA_IMAGE_NUMBER == 1)
  RE_IMAGE_FLASH_ADDRESS_DATA_SECURE = (FLASH_BASE_ADDRESS+FLASH_AREA_4_OFFSET),
#if !defined(MCUBOOT_PRIMARY_ONLY)
  RE_IMAGE_FLASH_DATA_SECURE_UPDATE = (FLASH_BASE_ADDRESS+FLASH_AREA_6_OFFSET),
#else
  RE_IMAGE_FLASH_DATA_SECURE_UPDATE = (FLASH_BASE_ADDRESS+FLASH_AREA_4_OFFSET),
#endif /* MCUBOOT_PRIMARY_ONLY */
  RE_IMAGE_FLASH_SECURE_DATA_IMAGE_SIZE = (FLASH_S_DATA_PARTITION_SIZE),
#else
  RE_IMAGE_FLASH_ADDRESS_DATA_SECURE = (0x0),
  RE_IMAGE_FLASH_DATA_SECURE_UPDATE = (0x0),
  RE_IMAGE_FLASH_SECURE_DATA_IMAGE_SIZE = (0x0),
#endif /* (MCUBOOT_S_DATA_IMAGE_NUMBER == 1) */
  RE_NS_DATA_IMAGE_NUMBER = (HEX(MCUBOOT_NS_DATA_IMAGE_NUMBER)),
#if (MCUBOOT_NS_DATA_IMAGE_NUMBER == 1)
  RE_IMAGE_FLASH_ADDRESS_DATA_NON_SECURE = (FLASH_BASE_ADDRESS+FLASH_AREA_5_OFFSET),
#if !defined(MCUBOOT_PRIMARY_ONLY)
  RE_IMAGE_FLASH_DATA_NON_SECURE_UPDATE = (FLASH_BASE_ADDRESS+FLASH_AREA_7_OFFSET),
#else
  RE_IMAGE_FLASH_DATA_NON_SECURE_UPDATE = (FLASH_BASE_ADDRESS+FLASH_AREA_5_OFFSET),
#endif /* MCUBOOT_PRIMARY_ONLY */
  RE_IMAGE_FLASH_NON_SECURE_DATA_IMAGE_SIZE = (FLASH_NS_DATA_PARTITION_SIZE),
#else
  RE_IMAGE_FLASH_ADDRESS_DATA_NON_SECURE = (0x0),
  RE_IMAGE_FLASH_DATA_NON_SECURE_UPDATE = (0x0),
  RE_IMAGE_FLASH_NON_SECURE_DATA_IMAGE_SIZE = (0x0),
#endif /* (MCUBOOT_NS_DATA_IMAGE_NUMBER == 1) */
  RE_BL2_PERSO_ADDRESS = (FLASH_BASE_ADDRESS+FLASH_AREA_PERSO_OFFSET),
  RE_BL2_BOOT_ADDRESS = (BL2_BOOT_VTOR_ADDR),
  /* area for programming hardening on page */
#if (FLASH_AREA_0_OFFSET+SECURE_IMAGE_MAX_SIZE) < (FLASH_B_SIZE)
  /* config without secure on bank 2 */
  RE_BL2_SEC1_END = (FLASH_AREA_0_OFFSET+SECURE_IMAGE_MAX_SIZE-0x1),
  RE_BL2_SEC2_START = (FLASH_B_SIZE-0x1),
  RE_BL2_SEC2_END = (0x0),
#else
  /* config with secure on bank 2 */
  RE_BL2_SEC1_END = (FLASH_B_SIZE-0x1),
  RE_BL2_SEC2_START = 0x0,
  RE_BL2_SEC2_END = (FLASH_AREA_0_OFFSET+SECURE_IMAGE_MAX_SIZE-FLASH_B_SIZE-0x1),
#endif /* (FLASH_AREA_0_OFFSET+SECURE_IMAGE_MAX_SIZE) < (FLASH_B_SIZE) */
  RE_BL2_WRP_START = (FLASH_AREA_PERSO_OFFSET),
  RE_BL2_WRP_END = (FLASH_AREA_BL2_NOHDP_OFFSET+FLASH_AREA_BL2_NOHDP_SIZE-0x1),
  RE_BL2_HDP_END = (FLASH_AREA_BL2_NOHDP_OFFSET-0x1),
  /* area for updates slot address */

#if defined(MCUBOOT_EXT_LOADER)
  RE_IMAGE_FLASH_LOADER_ADDRESS = (FLASH_BASE_ADDRESS+FLASH_AREA_LOADER_OFFSET),
  RE_LOADER_NS_CODE_SIZE = (LOADER_NS_CODE_SIZE),
  RE_LOADER_IMAGE_S_CODE_SIZE = (LOADER_IMAGE_S_CODE_SIZE),
  RE_LOADER_WRP_START = (FLASH_AREA_LOADER_BANK_OFFSET),
  RE_LOADER_WRP_END = (FLASH_B_SIZE-0x1),
  RE_EXT_LOADER = (0x1),
#else
  RE_IMAGE_FLASH_LOADER_ADDRESS = (0x0),
  RE_LOADER_NS_CODE_SIZE = (0x0),
  RE_LOADER_IMAGE_S_CODE_SIZE = (0x0),
  RE_LOADER_WRP_START = (FLASH_B_SIZE - 0x1),
  RE_LOADER_WRP_END = (0x0),
  RE_EXT_LOADER = (0x0),
#endif /* MCUBOOT_EXT_LOADER */
  RE_CRYPTO_SCHEME = CRYPTO_SCHEME,
#if defined(MCUBOOT_ENC_IMAGES)
  RE_ENCRYPTION = (0x1),
#else
  RE_ENCRYPTION = (0x0),
#endif
#if defined(MCUBOOT_OVERWRITE_ONLY)
  RE_OVER_WRITE = (0x1),
#else
  RE_OVER_WRITE = (0x0),
#endif
#if defined(STM32U535xx) || defined(STM32U545xx)
  RE_FLASH_PAGE_NBR = (0x1F)
#elif defined(STM32U585xx) || defined(STM32U575xx)
  RE_FLASH_PAGE_NBR = (0x7F)
#elif defined (STM32U595xx) || defined (STM32U599xx) \
   || defined (STM32U5A5xx) || defined (STM32U5A9xx) \
   || defined (STM32U5F9xx) || defined (STM32U5G9xx) \
   || defined (STM32U5G7xx)
  RE_FLASH_PAGE_NBR = (0xFF)
#endif
};
